tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Website Name'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: website_short_description
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Website Short Description'
              instructions: 'What is this all about'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: website_allow_pinterest
            field:
              inline_label: 'Allow Pinterest pins?'
              inline_label_when_true: 'yes'
              default: true
              type: toggle
              display: 'Website Allow Pinterest'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: site_background_image
            field:
              max_files: 1
              mode: list
              container: site-assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Website Background Image'
              instructions: 'We recommend a dark image in portrait mode'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
